# Generated by Django 4.0 on 2021-12-21 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_user_name'),
        ('fitness', '0002_rename_enemy_health_enemy_health_fitness_guide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_score', models.IntegerField(null=True)),
                ('option', models.CharField(max_length=1)),
                ('rank_fitness_name', models.CharField(max_length=50)),
                ('rank_user_name', models.CharField(max_length=50)),
                ('fitness_index', models.ForeignKey(db_column='fitness_index', on_delete=django.db.models.deletion.DO_NOTHING, to='fitness.fitness')),
                ('user_index', models.ForeignKey(db_column='user_index', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'rank',
                'managed': True,
            },
        ),
    ]
