# Generated by Django 4.0 on 2021-12-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='stage',
            field=models.IntegerField(null=True),
        ),
    ]
