# Generated by Django 4.0 on 2021-12-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('enemy_index', models.BigAutoField(primary_key=True, serialize=False)),
                ('enemy_name', models.CharField(max_length=100)),
                ('health', models.IntegerField()),
                ('enemy_filename', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'enemy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('fitness_index', models.BigAutoField(primary_key=True, serialize=False)),
                ('fitness_name', models.CharField(max_length=100)),
                ('guide', models.TextField(default='')),
                ('video', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'fitness',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_index', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_filename', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'item',
                'managed': True,
            },
        ),
    ]
