# Generated by Django 4.0 on 2021-12-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('monster_index', models.BigAutoField(primary_key=True, serialize=False)),
                ('monster_name', models.CharField(max_length=100)),
                ('monster_health', models.IntegerField()),
            ],
            options={
                'db_table': 'monster',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Enemy',
        ),
    ]
