# Generated by Django 4.0 on 2021-12-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='enemy_health',
            new_name='health',
        ),
        migrations.AddField(
            model_name='fitness',
            name='guide',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fitness',
            name='video',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='enemy_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='fitness_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_filename',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
