# Generated by Django 3.2.10 on 2021-12-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_index', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('user_create', models.DateTimeField(blank=True, null=True)),
                ('level', models.IntegerField(default=1)),
                ('exp', models.BigIntegerField(default=0)),
                ('best_score_fit1', models.IntegerField(null=True)),
                ('best_score_fit2', models.IntegerField(null=True)),
                ('best_score_fit3', models.IntegerField(null=True)),
                ('best_score_fit4', models.IntegerField(null=True)),
                ('is_item_ironman', models.BooleanField(default=False)),
                ('is_item_suit', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
