# Generated by Django 4.0 on 2021-12-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_index', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('user_create', models.DateTimeField(blank=True, null=True)),
                ('level', models.IntegerField(default=1)),
                ('exp', models.BigIntegerField(default=0)),
                ('best_score', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
