# Generated by Django 4.0 on 2021-12-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='best_score',
            new_name='best_score_fit1',
        ),
        migrations.AddField(
            model_name='user',
            name='best_score_fit2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='best_score_fit3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='best_score_fit4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_item_ironman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_item_suit',
            field=models.BooleanField(default=False),
        ),
    ]
